// User
export const ERROR_RECEIVE_USER = 'ERROR_RECEIVE_USER';
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SUCCESS_SIGN_IN = 'SUCCESS_SIGN_IN';

export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';

export const REQUEST_CARDS_LIST = 'REQUEST_CARDS_LIST';
export const RECEIVE_CARDS_LIST = 'RECEIVE_CARDS_LIST';
export const ERROR_CARDS_LIST = 'ERROR_CARDS_LIST';

export const REQUEST_CARD_DETAIL = 'REQUEST_CARD_DETAIL';
export const RECEIVE_CARD_DETAIL = 'RECEIVE_CARD_DETAIL';
export const ERROR_CARD_DETAIL = 'ERROR_CARD_DETAIL';

export const REQUEST_CREATE_CARD = 'REQUEST_CREATE_CARD';
export const SUCCESS_CREATE_CARD = 'SUCCESS_CREATE_CARD';
export const ERROR_CREATE_CARD = 'ERROR_CREATE_CARD';

export const REQUEST_UPDATE_CARD = 'REQUEST_UPDATE_CARD';
export const SUCCESS_UPDATE_CARD = 'SUCCESS_UPDATE_CARD';
export const ERROR_UPDATE_CARD = 'ERROR_UPDATE_CARD';

export const REQUEST_DELETE_CARD = 'REQUEST_DELETE_CARD';
export const SUCCESS_DELETE_CARD = 'SUCCESS_DELETE_CARD';
export const ERROR_DELETE_CARD = 'ERROR_DELETE_CARD';

export const REQUEST_DECKS_LIST = 'REQUEST_DECKS_LIST';
export const RECEIVE_DECKS_LIST = 'RECEIVE_DECKS_LIST';
export const ERROR_DECKS_LIST = 'ERROR_DECKS_LIST';

export const CLEAR_CARD_ERRORS = 'CLEAR_CARD_ERRORS';

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';
